import { CardSizePreset, PaperDimensions, AlignmentSettings, CalibrationSettings, PrinterProfile } from '../types';

export const CARD_SIZE_PRESETS: CardSizePreset[] = [
  {
    id: 'cr80_standard',
    name: 'Actual Standard PVC Card (CR80)',
    widthMm: 85.6,
    heightMm: 54.0,
    category: 'id_standard',
    description: '85.6 × 54.0 mm actual international ISO/IEC 7810 ID-1 standard for PVC ID, ATM, Smart & National Cards.',
  },
  {
    id: 'pvc_die_cut',
    name: 'Compact Die-Cut (80 × 50 mm)',
    widthMm: 80.0,
    heightMm: 50.0,
    category: 'id_standard',
    description: 'Compact 80 × 50 mm (8:5 ratio) format used in small card cutter dies.',
  },
  {
    id: 'aadhaar_cut',
    name: 'Aadhaar Card Cutout',
    widthMm: 80.0,
    heightMm: 50.0,
    category: 'government',
    description: 'Optimized 80 × 50 mm pocket cutout for official e-Aadhaar PDF printouts.',
  },
  {
    id: 'pan_card',
    name: 'PAN Card Standard',
    widthMm: 85.6,
    heightMm: 54.0,
    category: 'government',
    description: '85.6 × 54 mm exact physical print for NSDL / UTIITSL PAN cards.',
  },
  {
    id: 'ayushman_card',
    name: 'Ayushman Bharat (PM-JAY)',
    widthMm: 85.0,
    heightMm: 54.0,
    category: 'government',
    description: 'Golden Health Card physical size.',
  },
  {
    id: 'abha_card',
    name: 'ABHA Health ID Card',
    widthMm: 85.6,
    heightMm: 54.0,
    category: 'government',
    description: 'Digital Health Mission ID Card format.',
  },
  {
    id: 'eshram_card',
    name: 'e-Shram National Card',
    widthMm: 85.0,
    heightMm: 54.0,
    category: 'government',
    description: 'UAN unorganized workers identity card.',
  },
  {
    id: 'ration_card',
    name: 'Digital Ration PVC Card',
    widthMm: 85.6,
    heightMm: 54.0,
    category: 'government',
    description: 'NFSA Smart Ration Card.',
  },
  {
    id: 'employee_badge',
    name: 'Employee Badge / School ID',
    widthMm: 80.0,
    heightMm: 50.0,
    category: 'id_standard',
    description: 'Standard institutional PVC laminate size.',
  },
];

export const PAPER_SIZE_PRESETS: PaperDimensions[] = [
  {
    key: 'a4',
    name: 'A4 Sheet (210 × 297 mm)',
    widthMm: 210,
    heightMm: 297,
    description: 'Standard letter/office sheet. Best for 1, 2, 4, or 8 cards with manual cutting.',
  },
  {
    key: 'a5',
    name: 'A5 Sheet (148 × 210 mm)',
    widthMm: 148,
    heightMm: 210,
    description: 'Half A4 sheet. Common for desktop photo printers.',
  },
  {
    key: '4x6',
    name: '4 × 6 Photo Paper (101.6 × 152.4 mm)',
    widthMm: 101.6,
    heightMm: 152.4,
    description: 'Direct glossy photo card insert for rear tray.',
  },
  {
    key: 'canon_tray',
    name: 'Canon 2-Card PVC Tray (130 × 220 mm)',
    widthMm: 130,
    heightMm: 220,
    description: 'Dedicated plastic tray for Canon G-series, TS707, iP7270, MX922, etc.',
  },
  {
    key: 'custom',
    name: 'Custom Dimensions',
    widthMm: 210,
    heightMm: 297,
    description: 'Define your own sheet or tray measurements in mm.',
  },
];

export const DEFAULT_CALIBRATION: CalibrationSettings = {
  offsetX: 0.0,
  offsetY: 0.0,
  scaleCorrectionPct: 100.0,
};

export const DEFAULT_ALIGNMENT: AlignmentSettings = {
  paperSizeKey: 'a4',
  paperWidthMm: 210,
  paperHeightMm: 297,
  cardWidthMm: 85.6,
  cardHeightMm: 54.0,
  placementMode: 'top_center',
  centerOnPage: true,
  topMarginMm: 20.0,
  originXMm: 62.2, // (210 - 85.6) / 2 = 62.2mm (Centered horizontally on A4)
  originYMm: 20.0, // Top margin: 20.0mm from the top edge of A4 (range on A4: 0 to 243mm)
  multiCardLayout: {
    enabled: false,
    rows: 1,
    columns: 1,
    gapXMm: 10.0,
    gapYMm: 10.0,
  },
  backSheetFlipType: 'flip_short_edge',
  backFlipMode: 'none',
  backOffsetX: 0.0,
  backOffsetY: 0.0,
  copies: 1,
};

export const DEFAULT_PROFILES: PrinterProfile[] = [
  {
    id: 'canon_a4_top_center',
    name: 'Canon A4 Sheet (Actual PVC CR-80 Top & Center)',
    description: 'Actual standard PVC card (85.6 × 54.0 mm) centered horizontally on A4 (X: 62.2mm, Y: 20.0mm). Front and back print at the exact same location.',
    isDefault: true,
    alignment: {
      paperSizeKey: 'a4',
      paperWidthMm: 210,
      paperHeightMm: 297,
      cardWidthMm: 85.6,
      cardHeightMm: 54.0,
      placementMode: 'top_center',
      centerOnPage: true,
      topMarginMm: 20.0,
      originXMm: 62.2,
      originYMm: 20.0,
      multiCardLayout: {
        enabled: false,
        rows: 1,
        columns: 1,
        gapXMm: 10,
        gapYMm: 10,
      },
      backSheetFlipType: 'flip_short_edge',
      backFlipMode: 'none',
      backOffsetX: 0,
      backOffsetY: 0,
      copies: 1,
    },
    calibration: {
      offsetX: 0,
      offsetY: 0,
      scaleCorrectionPct: 100,
    },
    createdAt: 1710000000000,
    updatedAt: 1710000000000,
  },
  {
    id: 'canon_a4_centered',
    name: 'Canon A4 Sheet (Dead Center of Page)',
    description: 'Middle-of-page printing on A4 sheet (X: 65mm, Y: 123.5mm) in the dead center.',
    alignment: {
      paperSizeKey: 'a4',
      paperWidthMm: 210,
      paperHeightMm: 297,
      cardWidthMm: 80.0,
      cardHeightMm: 50.0,
      placementMode: 'page_center',
      centerOnPage: true,
      topMarginMm: 20.0,
      originXMm: 65.0,
      originYMm: 123.5,
      multiCardLayout: {
        enabled: false,
        rows: 1,
        columns: 1,
        gapXMm: 10,
        gapYMm: 10,
      },
      backSheetFlipType: 'flip_short_edge',
      backFlipMode: 'none',
      backOffsetX: 0,
      backOffsetY: 0,
      copies: 1,
    },
    calibration: {
      offsetX: 0,
      offsetY: 0,
      scaleCorrectionPct: 100,
    },
    createdAt: 1710000000000,
    updatedAt: 1710000000000,
  },
  {
    id: 'canon_tray_default',
    name: 'Canon Dedicated PVC Tray (Slot 1)',
    description: 'Standard 2-card PVC tray for Canon G2000, G3000, TS707, iP7270. Slot 1 front & back.',
    alignment: {
      paperSizeKey: 'canon_tray',
      paperWidthMm: 130,
      paperHeightMm: 220,
      cardWidthMm: 80.0,
      cardHeightMm: 50.0,
      placementMode: 'custom',
      centerOnPage: false,
      topMarginMm: 35.0,
      originXMm: 25.0,
      originYMm: 35.0,
      multiCardLayout: {
        enabled: false,
        rows: 1,
        columns: 1,
        gapXMm: 0,
        gapYMm: 0,
      },
      backSheetFlipType: 'tray_same_coords',
      backFlipMode: 'none',
      backOffsetX: 0,
      backOffsetY: 0,
      copies: 1,
    },
    calibration: {
      offsetX: 0,
      offsetY: 0,
      scaleCorrectionPct: 100,
    },
    createdAt: 1710000000000,
    updatedAt: 1710000000000,
  },
  {
    id: 'canon_4x6_single',
    name: 'Canon 4 × 6" Direct Photo Sheet',
    description: 'Card centered on 4x6 photo paper for borderless rear-tray printing.',
    alignment: {
      paperSizeKey: '4x6',
      paperWidthMm: 101.6,
      paperHeightMm: 152.4,
      cardWidthMm: 80.0,
      cardHeightMm: 50.0,
      placementMode: 'page_center',
      centerOnPage: true,
      topMarginMm: 20.0,
      originXMm: 10.8,
      originYMm: 51.2,
      multiCardLayout: {
        enabled: false,
        rows: 1,
        columns: 1,
        gapXMm: 0,
        gapYMm: 0,
      },
      backSheetFlipType: 'flip_short_edge',
      backFlipMode: 'none',
      backOffsetX: 0,
      backOffsetY: 0,
      copies: 1,
    },
    calibration: {
      offsetX: 0,
      offsetY: 0,
      scaleCorrectionPct: 100,
    },
    createdAt: 1710000000000,
    updatedAt: 1710000000000,
  },
];
